// Code generated by hertz generator.

package candyAgent

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _healthcheckMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendheartbeatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _executetaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _alert_ruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _syncMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createalertruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletealertruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getalertruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listalertruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _syncalertruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatealertruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

// 添加任务管理相关的中间件
func _gettaskstatusMw() []app.HandlerFunc {
	return nil
}

func _canceltaskMw() []app.HandlerFunc {
	return nil
}

func _gettaskresultMw() []app.HandlerFunc {
	return nil
}

func _readycheckMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _alert_rulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _alert_rules0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _heartbeatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tasksMw() []app.HandlerFunc {
	// your code...
	return nil
}
